### User Login ####

POST http://127.0.0.1:5000/users/login
Content-Type: application/json

{
    "user_name": "user1",
    "password": "Ab1234"
}

### Refresh access tokens ###
https://127.0.0.1:5000/users/refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk1MTMxNTYsIm5iZiI6MTU3OTUxMzE1NiwianRpIjoiZWQ3ZThiMzktMTdlOS00N2VjLThlYWMtMDQzYWMyOTg1Njk1IiwiZXhwIjoxNTc5Njg1OTU2LCJpZGVudGl0eSI6MSwidHlwZSI6InJlZnJlc2gifQ.l6Eru82G4jMasDmeHskp6_vI7bLCYCpM3x_KFSGfdjM

### User logout ###
DELETE http://127.0.0.1:5000/users/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk1MDk0MjksIm5iZiI6MTU3OTUwOTQyOSwianRpIjoiZWUyYzBhMjAtOWUwMy00NTA0LWI0ODUtNzMxM2I0MmY5MTcxIiwiZXhwIjoxNTc5NTEwMzI5LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6InBhdGllbnQifX0.G-dQd_zFWyaPe2GfHWdkvzwutjK8tql4iXXtSBx6Bc0

### Revoke refresh token ###
DELETE https://127.0.0.1:5000/users/logout_refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk1MTMxNTYsIm5iZiI6MTU3OTUxMzE1NiwianRpIjoiZWQ3ZThiMzktMTdlOS00N2VjLThlYWMtMDQzYWMyOTg1Njk1IiwiZXhwIjoxNTc5Njg1OTU2LCJpZGVudGl0eSI6MSwidHlwZSI6InJlZnJlc2gifQ.l6Eru82G4jMasDmeHskp6_vI7bLCYCpM3x_KFSGfdjM

#####################################################
#####################################################

### GET all patients ###
http://127.0.0.1:5000/users/patients
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk4NTcyNzgsIm5iZiI6MTU3OTg1NzI3OCwianRpIjoiNTUwZjczNDAtNWY5My00ZWM3LWFmNjItZDU5MDU1YzVmNDQzIiwiZXhwIjoxNTc5ODU4MTc4LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19.UuDyIpGl5agYM5WaPLTo2H3S8cgJ2Or1E-jAz2UIQkw

### GET specific patient ###
http://127.0.0.1:5000/users/patients/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk2MDgwMjUsIm5iZiI6MTU3OTYwODAyNSwianRpIjoiNzljNDE1OGUtMWQzNC00OTdkLTljNzItZjA4ZGQyMjc3NjhlIiwiZXhwIjoxNTc5NjA4OTI1LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6InBhdGllbnQifX0.Kofw-8Nce85Zy4scLS-dzhFWNnQNyXsPIuu0LPV1d6U

### CREATE patient ####

POST https://127.0.0.1:5000/users/patients
Content-Type: application/json

{
    "user_name": "user3",
    "first_name": "user",
    "last_name": "name",
    "gender": "male",
    "dob": "2000-01-02",
    "phone_no": "+254723467193",
    "email": "swaer@gmail.com",
    "password": "Ab1234",
    "status": "active"
}

### UPDATE patient ####

PUT https://127.0.0.1:5000/users/patients/1
Content-Type: application/json

{
    "last_name": "juma"
}

### DELETE patient ####

DELETE  https://127.0.0.1:5000/users/patients/1
Content-Type: application/json

#####################################################
#####################################################

### GET patient profiles ###
http://127.0.0.1:5000/profiles/patients
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODAxMDk1ODYsIm5iZiI6MTU4MDEwOTU4NiwianRpIjoiNTY1YmE2MzQtYWFiOC00ZjcxLWExNjAtYjQ4YWNjYmY1MjUyIiwiZXhwIjoxNTgwMTEwNDg2LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19.zZS6kKC1xRmGT5RJaoBeLH2pMBFekBsZk_RVkJUH-Hw

### CREATE patient profile ####
POST http://127.0.0.1:5000/profiles/patients
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk4NTQ3MTgsIm5iZiI6MTU3OTg1NDcxOCwianRpIjoiNWJlZDlmOTItMDE0Yy00OGQxLWIwYWQtOWViMDc0NjU0YzRiIiwiZXhwIjoxNTc5ODU1NjE4LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19._XPf09xuOXextigsa9mPzsdrO53C_tFx23uoJ5DY10Q

{
    "profile_pic": "user3.jpg",
    "country": "user",
    "state": "name",
    "location": "male"
}

### GET specific patient profile ###
http://127.0.0.1:5000/profiles/patients/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk4NTQ3MTgsIm5iZiI6MTU3OTg1NDcxOCwianRpIjoiNWJlZDlmOTItMDE0Yy00OGQxLWIwYWQtOWViMDc0NjU0YzRiIiwiZXhwIjoxNTc5ODU1NjE4LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19._XPf09xuOXextigsa9mPzsdrO53C_tFx23uoJ5DY10Q

### UPDATE patient profile ####

PUT http://127.0.0.1:5000/profiles/patients/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk4NTc3OTgsIm5iZiI6MTU3OTg1Nzc5OCwianRpIjoiODk2YTRmZGQtOWQ1ZC00YTgxLWFiNTMtN2U1NDBkZGRkYWVjIiwiZXhwIjoxNTc5ODU4Njk4LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19.8pVbRCt_sH8sP8wIp2ZzQCxu06R9xSlC-by0j1sBT6o

{
    "country": "kenya"
}

### DELETE patient profile ####

DELETE  http://127.0.0.1:5000/profiles/patients/3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk3Njk1MzEsIm5iZiI6MTU3OTc2OTUzMSwianRpIjoiNGNmNjI1Y2QtMzJiOS00YWM4LWJmMGQtN2M3ODY1YzQyYzdkIiwiZXhwIjoxNTc5NzcwNDMxLCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19.uIluIBmCp3SJTS64T0b0TyZPuZ_LoZSOe-8hN0J4qJU

#####################################################
#####################################################

### GET doctor profiles ###
http://127.0.0.1:5000/profiles/doctors
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODAyMzQyMjMsIm5iZiI6MTU4MDIzNDIyMywianRpIjoiYzhhM2NkMmMtZTEyNy00MDY3LThhZTQtNTZkZWM3ZDVmZDBlIiwiZXhwIjoxNTgwMjM1MTIzLCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19.XV8Sns3KuYAcIYYimOFFHGAs7XZbE64dGEiX8XY1YAU

### CREATE doctor profile ####
POST http://127.0.0.1:5000/profiles/doctors
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODAyMzc3MTcsIm5iZiI6MTU4MDIzNzcxNywianRpIjoiYjZiZjYxYzEtYTQwNy00YjllLWEzY2UtOTRlNDE0MzkyNjBjIiwiZXhwIjoxNTgwMjM4NjE3LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19.nNsTMwX0r1Hi33nirfKbaXjfNOaATLyY9FhXY0HCjjs

{
    "specialty": "orphthalmologist",
    "bio": "I am available all days of the week"
}

### GET specific doctor profile ###
http://127.0.0.1:5000/profiles/doctors/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODAyNzU2MzYsIm5iZiI6MTU4MDI3NTYzNiwianRpIjoiOGM5ZGVjZDUtZjVlNS00MzYwLWEyMDYtM2UzMGU1N2FiYjg1IiwiZXhwIjoxNTgwMjc2NTM2LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19.UiExJlpdbdtlYDLmJh1oubZwUbc7X8tE4XU79nRqmuo

### UPDATE doctor profile ####

PUT http://127.0.0.1:5000/profiles/doctors/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODAyNzY3NTAsIm5iZiI6MTU4MDI3Njc1MCwianRpIjoiNzI0ZjBhZGMtNTNmMy00NDVjLWEzMGQtM2IwMjNjMWFhMTYyIiwiZXhwIjoxNTgwMjc3NjUwLCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19.ycRj8xm07yVm64Vx6B3CT8YE0_2vXoVc8KSAYmypvPQ

{
    "specialty": "opthalmologist"
}

### DELETE patient profile ####

DELETE  http://127.0.0.1:5000/profiles/patients/3
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk3Njk1MzEsIm5iZiI6MTU3OTc2OTUzMSwianRpIjoiNGNmNjI1Y2QtMzJiOS00YWM4LWJmMGQtN2M3ODY1YzQyYzdkIiwiZXhwIjoxNTc5NzcwNDMxLCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6ImFkbWluIn19.uIluIBmCp3SJTS64T0b0TyZPuZ_LoZSOe-8hN0J4qJU

#####################################################
#####################################################

### GET all roles ###
https://127.0.0.1:5000/users/roles

### GET specific role ###
http://127.0.0.1:5000/users/roles/20

### CREATE new role ####

POST https://127.0.0.1:5000/users/roles
Content-Type: application/json

{
    "role": "admin",
    "code": 1
}

### UPDATE role ####

PUT https://127.0.0.1:5000/users/roles/4
Content-Type: application/json

{
    "role": "patient"
}

### DELETE role ####

DELETE  https://127.0.0.1:5000/users/roles/2
Content-Type: application/json
