### GET all patients ###
http://127.0.0.1:5000/users/patients

### GET specific patient ###
http://127.0.0.1:5000/users/patients/20

### CREATE patient ####

POST http://127.0.0.1:5000/users/patients
Content-Type: application/json

{
    "user_name": "user3",
    "first_name": "user",
    "last_name": "name",
    "gender": "male",
    "dob": "2000-01-02",
    "phone_no": "+254723467193",
    "email": "swaer@gmail.com",
    "password": "Ab1234",
    "status": "active"
}

### UPDATE patient ####

PUT http://127.0.0.1:5000/users/patients/1
Content-Type: application/json

{
    "last_name": "juma"
}

### DELETE patient ####

DELETE  http://127.0.0.1:5000/users/patients/1
Content-Type: application/json

### GET all roles ###
http://127.0.0.1:5000/users/roles

### GET specific role ###
http://127.0.0.1:5000/users/roles/20

### CREATE new role ####

POST http://127.0.0.1:5000/users/roles
Content-Type: application/json

{
    "role": "admin",
    "code": 1
}

### UPDATE role ####

PUT http://127.0.0.1:5000/users/roles/4
Content-Type: application/json

{
    "role": "patient"
}

### DELETE patient ####

DELETE  http://127.0.0.1:5000/users/roles/2
Content-Type: application/json
