### User Login ####

POST https://ignite-backend.azurewebsites.net/users/login
Content-Type: application/json

{
    "user_name": "user1",
    "password": "Ab1234"
}

### Refresh access tokens ###
https://ignite-backend.azurewebsites.net/users/refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk1MTMxNTYsIm5iZiI6MTU3OTUxMzE1NiwianRpIjoiZWQ3ZThiMzktMTdlOS00N2VjLThlYWMtMDQzYWMyOTg1Njk1IiwiZXhwIjoxNTc5Njg1OTU2LCJpZGVudGl0eSI6MSwidHlwZSI6InJlZnJlc2gifQ.l6Eru82G4jMasDmeHskp6_vI7bLCYCpM3x_KFSGfdjM

### User logout ###
DELETE http://127.0.0.1:5000/users/logout
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk1MDk0MjksIm5iZiI6MTU3OTUwOTQyOSwianRpIjoiZWUyYzBhMjAtOWUwMy00NTA0LWI0ODUtNzMxM2I0MmY5MTcxIiwiZXhwIjoxNTc5NTEwMzI5LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6InBhdGllbnQifX0.G-dQd_zFWyaPe2GfHWdkvzwutjK8tql4iXXtSBx6Bc0

### Revoke refresh token ###
DELETE https://ignite-backend.azurewebsites.net/users/logout_refresh
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk1MTMxNTYsIm5iZiI6MTU3OTUxMzE1NiwianRpIjoiZWQ3ZThiMzktMTdlOS00N2VjLThlYWMtMDQzYWMyOTg1Njk1IiwiZXhwIjoxNTc5Njg1OTU2LCJpZGVudGl0eSI6MSwidHlwZSI6InJlZnJlc2gifQ.l6Eru82G4jMasDmeHskp6_vI7bLCYCpM3x_KFSGfdjM

### GET all patients ###
http:https://ignite-backend.azurewebsites.net/users/patients
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk1MDk0MjksIm5iZiI6MTU3OTUwOTQyOSwianRpIjoiZWUyYzBhMjAtOWUwMy00NTA0LWI0ODUtNzMxM2I0MmY5MTcxIiwiZXhwIjoxNTc5NTEwMzI5LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6InBhdGllbnQifX0.G-dQd_zFWyaPe2GfHWdkvzwutjK8tql4iXXtSBx6Bc0

### GET specific patient ###
http://127.0.0.1:5000/users/patients/3
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1Nzk2MDgwMjUsIm5iZiI6MTU3OTYwODAyNSwianRpIjoiNzljNDE1OGUtMWQzNC00OTdkLTljNzItZjA4ZGQyMjc3NjhlIiwiZXhwIjoxNTc5NjA4OTI1LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIiwidXNlcl9jbGFpbXMiOnsicm9sZSI6InBhdGllbnQifX0.Kofw-8Nce85Zy4scLS-dzhFWNnQNyXsPIuu0LPV1d6U

### CREATE patient ####

POST https://ignite-backend.azurewebsites.net/users/patients
Content-Type: application/json

{
    "user_name": "user3",
    "first_name": "user",
    "last_name": "name",
    "gender": "male",
    "dob": "2000-01-02",
    "phone_no": "+254723467193",
    "email": "swaer@gmail.com",
    "password": "Ab1234",
    "status": "active"
}

### UPDATE patient ####

PUT https://ignite-backend.azurewebsites.net/users/patients/1
Content-Type: application/json

{
    "last_name": "juma"
}

### DELETE patient ####

DELETE  https://ignite-backend.azurewebsites.net/users/patients/1
Content-Type: application/json

### GET all roles ###
https://ignite-backend.azurewebsites.net/users/roles

### GET specific role ###
http://127.0.0.1:5000/users/roles/20

### CREATE new role ####

POST https://ignite-backend.azurewebsites.net/users/roles
Content-Type: application/json

{
    "role": "admin",
    "code": 1
}

### UPDATE role ####

PUT https://ignite-backend.azurewebsites.net/users/roles/4
Content-Type: application/json

{
    "role": "patient"
}

### DELETE patient ####

DELETE  https://ignite-backend.azurewebsites.net/users/roles/2
Content-Type: application/json
