# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'a57a9bf9-b5a2-42ae-b2f9-8f1a6a983ec4'
  
  # Web app name
  webAppNameDev: 'ignite-backend'
  webAppNameTest: 'ignite-backend-Test'
  webAppNameStaging: 'ignite-backend-staging'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  environmentNameDev: 'ignite-backend'
  environmentNameTest: 'ignite-backend-test'
  environmentNameStaging: 'ignite-backend-staging'

  # Project root folder. Point to the folder containing manage.py file.
  projectRoot: $(System.DefaultWorkingDirectory)
  
  # Python version: 3.7
  pythonVersion: '3.7'




stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python $(pythonVersion)'
    
    - script: |
        python3 -m venv antenv
        source antenv/bin/activate
        make install
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"
      
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python version'

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(pythonVersion)'
      displayName: 'Use Python version'
      
    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFiles: '**/test.*'
        testRunTitle: 'Publish test results for Python $(python.version)'

    - task: WhiteSource Bolt@20

      

    - task: PublishCodeCoverageResults@1
      inputs:
        codeCoverageTool: Cobertura
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop




- stage: Dev
  displayName: 'Deploy Web App to dev'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentNameDev)
    strategy:
      runOnce:
        deploy:
          steps:   

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : ignite-backend-Dev'
            inputs:
              appType: webAppLinux
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppNameDev)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip





- stage: Test
  displayName: 'Deploy Web App to test environment'
  dependsOn: Dev
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentNameTest)
    strategy:
      runOnce:
        deploy:
          steps:   

          - task: WhiteSource Bolt@20

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : ignite-backend-Test'
            inputs:
              appType: webAppLinux
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppNameTest)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip






- stage: Staging
  displayName: 'Deploy Web App to staging environment'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: $(environmentNameStaging)
    strategy:
      runOnce:
        deploy:
          steps:   

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : ignite-backend-Staging'
            inputs:
              appType: webAppLinux
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppNameStaging)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
      