"""create doctor profiles table

Revision ID: 326a435c7d48
Revises: bbed8a5ccbf7
Create Date: 2020-01-28 21:54:05.648249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326a435c7d48'
down_revision = 'bbed8a5ccbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'patient_profiles', ['profile_user'])
    op.create_table('doctor_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('patient_profile', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=250), nullable=True),
    sa.Column('bio', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['patient_profile'], ['patient_profiles.profile_user'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patient_profiles', type_='unique')
    op.drop_table('doctor_profiles')
    # ### end Alembic commands ###
