"""create user profiles table

Revision ID: bbed8a5ccbf7
Revises: d133607c824c
Create Date: 2020-01-22 12:03:12.290202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbed8a5ccbf7'
down_revision = 'd133607c824c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_profiles',
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_user', sa.Integer(), nullable=False),
    sa.Column('profile_pic', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=250), nullable=True),
    sa.Column('state', sa.String(length=250), nullable=True),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['profile_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient_profiles')
    # ### end Alembic commands ###
