name: CI

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make install
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
