name: CI

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_DATABASE_URL: postgresql://postgres:password@localhost:5432/test_db
      SECRET_KEY: aplicationsecretkey102noonecanrememberthislongtext

    services:
      postgres:
        image: postgres:10.10
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        make install
    - name: Lint with flake8
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
